"""enterprise foundation

Revision ID: 5e076f0f1815
Revises: 63c10e73092c
Create Date: 2026-04-26 17:51:47.390110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e076f0f1815'
down_revision = '63c10e73092c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    timestamp_default = sa.text('CURRENT_TIMESTAMP')
    op.create_table('ai_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('feature', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('request_units', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_logs_feature'), ['feature'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_logs_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_logs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_logs_user_id'), ['user_id'], unique=False)

    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('target_model', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=80), nullable=True),
    sa.Column('requester_user_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_requests_request_type'), ['request_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_requester_user_id'), ['requester_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_reviewer_user_id'), ['reviewer_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_target_model'), ['target_model'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_status'), ['status'], unique=False)

    op.create_table('meal_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_meal_template_school_name')
    )
    with op.batch_alter_table('meal_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_templates_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_templates_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_templates_school_id'), ['school_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('requested_ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_consumed_at'), ['consumed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('platform_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_jobs_scheduled_for'), ['scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_jobs_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('meal_template_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['meal_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_template_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_template_items_food_id'), ['food_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_template_items_meal_type'), ['meal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_template_items_template_id'), ['template_id'], unique=False)

    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_details.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_feedback_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_feedback_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_feedback_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_feedback_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recorded_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approval_status', sa.String(length=32), nullable=False, server_default='approved'))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=timestamp_default))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=timestamp_default))
        batch_op.create_index(batch_op.f('ix_attendance_approval_status'), ['approval_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_recorded_by_user_id'), ['recorded_by_user_id'], unique=False)
        batch_op.create_foreign_key('fk_attendance_recorded_by_user_id_users', 'users', ['recorded_by_user_id'], ['id'])

    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=timestamp_default))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=timestamp_default))
        batch_op.create_index(batch_op.f('ix_food_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_school_id'), ['school_id'], unique=False)
        batch_op.create_foreign_key('fk_food_school_id_users', 'users', ['school_id'], ['id'])
        batch_op.create_foreign_key('fk_food_created_by_user_id_users', 'users', ['created_by_user_id'], ['id'])

    with op.batch_alter_table('health_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=timestamp_default))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=timestamp_default))

    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=32), nullable=False, server_default='approved'))
        batch_op.add_column(sa.Column('recurrence_label', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('template_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=timestamp_default))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=timestamp_default))
        batch_op.create_index(batch_op.f('ix_meal_plan_approved_by_user_id'), ['approved_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_plan_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_plan_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_plan_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_plan_template_id'), ['template_id'], unique=False)
        batch_op.create_foreign_key('fk_meal_plan_approved_by_user_id_users', 'users', ['approved_by_user_id'], ['id'])
        batch_op.create_foreign_key('fk_meal_plan_created_by_user_id_users', 'users', ['created_by_user_id'], ['id'])
        batch_op.create_foreign_key('fk_meal_plan_template_id_meal_templates', 'meal_templates', ['template_id'], ['id'])

    with op.batch_alter_table('meal_plan_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=timestamp_default))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=timestamp_default))

    with op.batch_alter_table('student_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guardian_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('guardian_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('guardian_phone', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=32), nullable=False, server_default='active'))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=timestamp_default))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=timestamp_default))
        batch_op.create_index(batch_op.f('ix_student_details_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_details_status'), ['status'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('primary_student_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_password_change_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('session_version', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('can_manage_students', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('can_manage_meals', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('can_manage_attendance', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('can_view_reports', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('can_manage_staff', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('can_approve_workflows', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=timestamp_default))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=timestamp_default))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_primary_student_id'), ['primary_student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_school_id'), ['school_id'], unique=False)
        batch_op.create_foreign_key('fk_users_primary_student_id', 'student_details', ['primary_student_id'], ['id'], use_alter=True)
        batch_op.create_foreign_key('fk_users_school_id_users', 'users', ['school_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_school_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_users_primary_student_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_school_id'))
        batch_op.drop_index(batch_op.f('ix_users_primary_student_id'))
        batch_op.drop_index(batch_op.f('ix_users_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('can_approve_workflows')
        batch_op.drop_column('can_manage_staff')
        batch_op.drop_column('can_view_reports')
        batch_op.drop_column('can_manage_attendance')
        batch_op.drop_column('can_manage_meals')
        batch_op.drop_column('can_manage_students')
        batch_op.drop_column('session_version')
        batch_op.drop_column('last_password_change_at')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('primary_student_id')
        batch_op.drop_column('school_id')
        batch_op.drop_column('full_name')
        batch_op.drop_column('email')

    with op.batch_alter_table('student_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_details_status'))
        batch_op.drop_index(batch_op.f('ix_student_details_is_deleted'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('status')
        batch_op.drop_column('guardian_phone')
        batch_op.drop_column('guardian_email')
        batch_op.drop_column('guardian_name')

    with op.batch_alter_table('meal_plan_item', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.drop_constraint('fk_meal_plan_template_id_meal_templates', type_='foreignkey')
        batch_op.drop_constraint('fk_meal_plan_created_by_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_meal_plan_approved_by_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_meal_plan_template_id'))
        batch_op.drop_index(batch_op.f('ix_meal_plan_status'))
        batch_op.drop_index(batch_op.f('ix_meal_plan_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_meal_plan_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_meal_plan_approved_by_user_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('template_id')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by_user_id')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('recurrence_label')
        batch_op.drop_column('status')
        batch_op.drop_column('notes')
        batch_op.drop_column('title')

    with op.batch_alter_table('health_metrics', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_constraint('fk_food_created_by_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_food_school_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_food_school_id'))
        batch_op.drop_index(batch_op.f('ix_food_created_by_user_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint('fk_attendance_recorded_by_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_attendance_recorded_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_approval_status'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('approval_status')
        batch_op.drop_column('recorded_by_user_id')

    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_feedback_student_id'))
        batch_op.drop_index(batch_op.f('ix_user_feedback_status'))
        batch_op.drop_index(batch_op.f('ix_user_feedback_school_id'))

    op.drop_table('user_feedback')
    with op.batch_alter_table('meal_template_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_template_items_template_id'))
        batch_op.drop_index(batch_op.f('ix_meal_template_items_meal_type'))
        batch_op.drop_index(batch_op.f('ix_meal_template_items_food_id'))

    op.drop_table('meal_template_items')
    with op.batch_alter_table('platform_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_platform_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_platform_jobs_school_id'))
        batch_op.drop_index(batch_op.f('ix_platform_jobs_scheduled_for'))
        batch_op.drop_index(batch_op.f('ix_platform_jobs_job_type'))

    op.drop_table('platform_jobs')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_expires_at'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_consumed_at'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_school_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_category'))

    op.drop_table('notifications')
    with op.batch_alter_table('meal_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_templates_school_id'))
        batch_op.drop_index(batch_op.f('ix_meal_templates_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_meal_templates_created_by_user_id'))

    op.drop_table('meal_templates')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_status'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_school_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_requests_target_model'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_target_id'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_status'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_school_id'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_reviewer_user_id'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_requester_user_id'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_request_type'))

    op.drop_table('approval_requests')
    with op.batch_alter_table('ai_usage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_logs_status'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_logs_school_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_logs_feature'))

    op.drop_table('ai_usage_logs')
    # ### end Alembic commands ###
