"""initial schema

Revision ID: 63c10e73092c
Revises: 
Create Date: 2026-04-26 00:30:55.899085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c10e73092c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('fats', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('school_name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_school_name'), ['school_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('meal_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'plan_date', name='uq_meal_plan_school_date')
    )
    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_plan_plan_date'), ['plan_date'], unique=False)
        batch_op.create_index('ix_meal_plan_school_date', ['school_id', 'plan_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_plan_school_id'), ['school_id'], unique=False)

    op.create_table('student_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('roll_no', sa.Integer(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=10), nullable=False),
    sa.Column('activity_level', sa.String(length=50), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_details_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_details_roll_no'), ['roll_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_details_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_details_user_id'), ['user_id'], unique=True)

    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('ate_breakfast', sa.Boolean(), nullable=False),
    sa.Column('ate_lunch', sa.Boolean(), nullable=False),
    sa.Column('ate_dinner', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_details.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'attendance_date', name='uq_attendance_student_date')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_attendance_date'), ['attendance_date'], unique=False)
        batch_op.create_index('ix_attendance_student_date', ['student_id', 'attendance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_student_id'), ['student_id'], unique=False)

    op.create_table('health_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_metrics_record_date'), ['record_date'], unique=False)
        batch_op.create_index('ix_health_metrics_student_date', ['student_id', 'record_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_metrics_student_id'), ['student_id'], unique=False)

    op.create_table('meal_plan_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_plan_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_plan_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_plan_item_food_id'), ['food_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_plan_item_meal_plan_id'), ['meal_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_plan_item_meal_type'), ['meal_type'], unique=False)
        batch_op.create_index('ix_meal_plan_item_plan_food', ['meal_plan_id', 'food_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_plan_item', schema=None) as batch_op:
        batch_op.drop_index('ix_meal_plan_item_plan_food')
        batch_op.drop_index(batch_op.f('ix_meal_plan_item_meal_type'))
        batch_op.drop_index(batch_op.f('ix_meal_plan_item_meal_plan_id'))
        batch_op.drop_index(batch_op.f('ix_meal_plan_item_food_id'))

    op.drop_table('meal_plan_item')
    with op.batch_alter_table('health_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_metrics_student_id'))
        batch_op.drop_index('ix_health_metrics_student_date')
        batch_op.drop_index(batch_op.f('ix_health_metrics_record_date'))

    op.drop_table('health_metrics')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_student_id'))
        batch_op.drop_index('ix_attendance_student_date')
        batch_op.drop_index(batch_op.f('ix_attendance_attendance_date'))

    op.drop_table('attendance')
    with op.batch_alter_table('student_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_details_user_id'))
        batch_op.drop_index(batch_op.f('ix_student_details_school_id'))
        batch_op.drop_index(batch_op.f('ix_student_details_roll_no'))
        batch_op.drop_index(batch_op.f('ix_student_details_grade'))

    op.drop_table('student_details')
    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_plan_school_id'))
        batch_op.drop_index('ix_meal_plan_school_date')
        batch_op.drop_index(batch_op.f('ix_meal_plan_plan_date'))

    op.drop_table('meal_plan')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_school_name'))
        batch_op.drop_index(batch_op.f('ix_users_role'))

    op.drop_table('users')
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_name'))

    op.drop_table('food')
    # ### end Alembic commands ###
